### ISSUE TITLE
Data model does not support relationships between articles

### ISSUE THREAD

**Issue by TheBeege** [TheBeege/SciNet#1]
There's no relationship between articles. Examples include replication studies, dependencies, etc.

**Comment by anthonyselkowitz** [comment]
I think a hurdle would be to determine what would be a replication study and finding them in the first place. A crowd source of this info could be one way to do it.  Researchers will be knowledgeable about a certain area and are often willing to provide info about this stuff.

**Comment by TheBeege** [comment]
Aye, that's what I was thinking. Do we want to have some threshold of researchers agreeing it's a replication study before marking it as such? Then again, we can always set it up to be configurable and tune it as time goes on.

**Comment by TheBeege** [comment]
Going to close this as the relationship has been addressed in the data model. Going to open a new issue around how to identify replication studies.
