### ISSUE TITLE
Store articles ourselves?

### ISSUE THREAD

**Issue by anthonyselkowitz** [TheBeege/SciNet#2]
![firstpass](https://cloud.githubusercontent.com/assets/7175420/16543022/531b422a-408e-11e6-91c0-fd8dde2ec15f.png)

In this you mention PDFs. We might have an issue about storing PDFs because typically those have a copyright and copyright holders. There could be a way to get around this by having links like Google Scholar does to their original sources like Elsevier and the like.   

Would we be giving people access to the PDFs?

**Comment by TheBeege** [comment]
Mmm... I should have fleshed out the readme and just generally discussed this more. 

The intent is to have people directly upload to this system with the understanding that the article will be publicly viewable. If you think this isn't ideal, I'm curious to hear why so we can brainstorm alternatives.

**Comment by DesireeVanHaute** [comment]
You should check to see how Research Gate deals with this problem (uploading papers). Some journals will allow it but others won't. 

Links may be an easy way around it. Check out Faculty 1000. I don't think they host articles but they highlight them with commentary and then I think include a link (I can't confirm because I'm currently limited to my phone due to a melting computer charger).

**Comment by TheBeege** [comment]
Excellent suggestions, thank you!

Seems like we're aiming for a combination of both these products - the speed and data features of F1000 combined with the relationship and free aspects of ResearchGate. Also, relevant blog post from F1000: http://blog.f1000research.com/2016/06/22/giving-researchers-credit-for-their-data-enters-phase-3/. I wasn't considering integrating with publishers directly, but that's an interesting concept. I ideally want to replace the publishers, but I'm not sure that's realistic.

But yes, F1000 relies on other cloud storage methods, though it seems they're investigating using Microsoft Azure. 

ResearchGate just reminded me of a component I forgot - citations. That's how we handle the dependencies. I thought of that towards the start but forgot about it. I'll create a separate issue for that.

Regarding discussion, do you feel like a site like this would be the appropriate place for it? Or do you think researchers would prefer to pursue discussion over a different medium?

**Comment by TheBeege** [comment]
I filled out the README a bit more to be clearer around the features we want to provide: 80a13daf69c48c41bdc24ad7f12271795a3a2254. I expect a bunch of this to trigger "we can't do that" or "there's no value in that" responses, so please, tear it apart for me so we can identify what's possible.

**Comment by DesireeVanHaute** [comment]
In general I don't read the discussions on papers (when they exist). Anonymity makes people mean and using real names tends to keep people too polite. So I don't know. Pubpeer is set up for post publication review and I'm not sure how much buy in they have had for discussion.

**Comment by anthonyselkowitz** [comment]
I concur. Discussion on these things can lead to toxicity and unless there's a systematic way to curb toxicity, I don't think it would be fruitful for a system like this. 

Edit: On further consideration, a discussion system, if working, would be really helpful for authors.

**Comment by TheBeege** [comment]
Hmm... For now, I'm thinking we consider discussion a potential feature that definitely would not be a part of MVP. That'll give us more time to think on it, and I don't think it's absolutely critical to the core objective.

**Comment by TheBeege** [comment]
Also, I did a bad job of keeping this thread on topic. I definitely want to link to publications. Do we want to host pre-publication papers ourselves? Are we undecided? We could always defer this to after minimum viable product.

**Comment by anthonyselkowitz** [comment]
I think that hosting the pre-publications ourselves would be a good idea. From my interviews with the users (all psych researchers) they felt like a pre-publications site that focused on null-results and replication would be something that they would be comfortable with using. (Note that people in other disciplines would feel comfortable with pre-pubs in addition presenting null results and replications.)

**Comment by anthonyselkowitz** [comment]
I think another question that we should address is whether or not the product should also host their other publications in journals as well. This would make it similar to research gate, but I think that if we emphasize the replication aspects and the null results aspect it would make us different enough to carve out our own space.

**Comment by TheBeege** [comment]
I like the idea of focusing on null-results and replication, at least at first. In that case, we should be hosting those types of articles, so that closes this issue.

Host their other publications in journals? Not sure I understand. Are you saying we should push publication requests from our product to journals? Gonna say we should open up a separate issue for this point. 

Thanks
