### ISSUE TITLE
Peer reviews

### ISSUE THREAD

**Issue by TheBeege** [TheBeege/SciNet#4]
Per Akshat, how do we plan on supporting peer reviews?

**Comment by TheBeege** [comment]
Comment from Akshat:
Would not recommend gamification as none of us have literally anything to offer researchers (short of funding). Would suggest allowing site to function as preprint server but with a topic dependency graph - in other words, scientists can only provide preprints of papers due to be published elsewhere (they take care of peer review, etc.), but can add their paper and the resulting conclusions as a tentative node in a graph tracking milestones in a research topic. When the paper is formally published, scientists can offer proof of publication and the tentative node is upgraded to a definitive node.

**Comment by anthonyselkowitz** [comment]
Yeah, there are a few open access journals out there right now. Though, I'm not sure if they charge a fee to the author of the article or if it makes money from donations. 

There's a lot of issues in science where ideas a basically stolen because of the competition for tenure. It's known as "publish or perish", so I'm not sure there would be much incentive for scientists to pre-publish an article outside of a conference. If it really is groundbreaking enough to lead to a publication then it is likely that someone would do everything in their power to scoop that finding and publish it before they do.

**Comment by anthonyselkowitz** [comment]
*Will look more into preprints.

**Comment by TheBeege** [comment]
I see us as mailing a copy of your work in the mail to yourself. It is seen as reliable and a solid proof of what came first.

Of course, we're not a government-backed organization like the postal service, but if we can acquire enough researchers, that could help. Additionally, we could have our cake and eat it, too... We could allow researchers to upload their works _and_ crawl existing publications to reference. Would have to purchase access to these, but I'm okay with that. I eventually intend to make this a non-profit, so there would be an organization to receive and disseminate funds.

Thoughts? If you agree with uploading and referencing, I'll update the architecture diagram accordingly.

**Comment by TheBeege** [comment]
Created a table called "review" that ties an author to an article with a timestamp that indicates that author has reviewed the article. 

Still need to do the logistics stuff like normal "users" and tying them to authors etc etc.

**Comment by DesireeVanHaute** [comment]
WRT open access the current model is the author pays a fee (generally more than standard publication costs) and the paper is free to download for the readers.

**Comment by TheBeege** [comment]
Seems like an opportunity, then, if we can keep it cheap/free. My hope is that we can survive from donations and maybe grants. Regardless, server costs are still relatively low, and I hope that the users are trustworthy enough for curation.

**Comment by TheBeege** [comment]
I'm going to close this one and open a new one for anonymity and peer reviews.
